"""small-1x.png -> hand fixes + a short glow -> small-final.png, ../luciole-small.js and the CLI's
packages/luciole/src/mascot-sprite.gen.ts (what `luciole init` greets with).

The small mascot (terminal, tiny avatars) is its own drawing, not a reduction.
Edit small-1x.png by hand to change it, then re-run this script.
"""
import json
import numpy as np
from PIL import Image

a = np.asarray(Image.open("small-1x.png").convert("RGBA")).astype(int)
H, W = a.shape[:2]
CREAM = (225, 197, 150)
# Antenna stalks: Gemini drew them in the outline navy, invisible on a dark terminal.
for y, x in ((3, 6), (4, 7), (5, 8), (3, 17), (4, 16), (5, 15)):
    a[y, x] = (*CREAM, 255)

# Room for the glow around the drawing.
PAD = 3
a = np.pad(a, ((PAD, PAD), (PAD, PAD), (0, 0)))
H, W = a.shape[:2]

# Glow: two short rings around the lantern and the antenna tips, on transparent cells only.
GLOW = (198, 232, 90)
def is_light(y, x):
    r, g, b, al = a[y, x]
    return al == 255 and g > 180 and g > r + 20  # the lantern's and tips' greens
sources = [(y, x) for y in range(H) for x in range(W) if is_light(y, x)]
TIPS_BELOW = 10  # rows above this hold the antenna tips (padded coordinates)
glow = np.zeros((H, W))
for y in range(H):
    for x in range(W):
        if a[y, x, 3]: continue
        d_lantern = min((np.hypot(y - sy, x - sx) for sy, sx in sources if sy >= TIPS_BELOW), default=99)
        d_tip = min((np.hypot(y - sy, x - sx) for sy, sx in sources if sy < TIPS_BELOW), default=99)
        # Lantern: a solid ring and a sparse outer one. Tips: one solid ring only (a dithered
        # ring around such small discs reads as a cog).
        if d_lantern <= 2.3: glow[y, x] = 0.42
        elif d_lantern <= 3.3 and (x + y) % 2 == 0: glow[y, x] = 0.22
        elif d_tip <= 2.3: glow[y, x] = 0.34
for y, x in zip(*np.where(glow > 0)):
    a[y, x] = (*GLOW, round(glow[y, x] * 255))

Image.fromarray(a.astype(np.uint8), "RGBA").save("small-final.png")
# JS module: palette of RGBA colours, one char per pixel.
ALPH = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
pal, idx, rows = [], {}, []
for y in range(H):
    row = ""
    for x in range(W):
        c = tuple(int(v) for v in a[y, x])
        if c[3] == 0: row += "."; continue
        if c not in idx: idx[c] = len(pal); pal.append(c)
        row += ALPH[idx[c]]
    rows.append(row)
hexes = ["#%02x%02x%02x%02x" % c for c in pal]
open("../luciole-small.js", "w").write(
    "// Generated by small/finalize.py from small/small-1x.png — the small mascot, drawn for its size\n"
    "// (terminal, tiny avatars). PIXELS: one char per pixel, index into PALETTE (#rrggbbaa), '.' = transparent.\n"
    f"export const W = {W}, H = {H};\nexport const PALETTE = {json.dumps(hexes)};\nexport const PIXELS = [\n"
    + "\n".join(f"  {json.dumps(r)}," for r in rows) + "\n];\n")
print(W, "x", H, len(pal), "colours")
CLI = "../../../../packages/luciole/src/mascot-sprite.gen.ts"
open(CLI, "w").write(
    "// Generated by website/design/mascot/small/finalize.py: the small mascot, drawn for terminal\n"
    "// size. One char per pixel, an index into MASCOT_PALETTE (#rrggbbaa); '.' is transparent.\n"
    "export const MASCOT_PALETTE: readonly string[] = [\n"
    + "".join(f'  "{h}",\n' for h in hexes) + "];\n\n"
    "export const MASCOT_PIXELS: readonly string[] = [\n"
    + "".join(f'  "{r}",\n' for r in rows) + "];\n")
print("wrote", CLI)
