// Generated by `airtty build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "airtty/route-tree";
import Layout0 from "./layout";
import Layout1 from "./notes/layout";
import Error2 from "./error";
import Loading3 from "./notes/[id]/loading";

const rootRoute = createRootRoute(Layout0);
const layout0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "notes",
  ...layoutRoute(Layout1, []),
});
const page0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/", []),
  ...pageRoute([], { error: Error2 }),
});
const page1Route = createRoute({
  getParentRoute: () => layout0Route,
  path: "$id",
  loader: (ctx) => loadPage(ctx, "/notes/[id]", ["id"]),
  ...pageRoute(["id"], { loading: Loading3, error: Error2 }),
});

export const routeTree = rootRoute.addChildren([layout0Route.addChildren([page1Route]), page0Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
