// Generated by `luciole build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "@luciole-sh/core/route-tree";
import Layout0 from "./layout";
import Error1 from "./error";
import Loading2 from "./notes/[id]/loading";
import NotFound3 from "./notes/[id]/not-found";

const rootRoute = createRootRoute(Layout0);
const page0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/", []),
  ...pageRoute([], { error: Error1 }),
});
const page1Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "notes/$id",
  loader: (ctx) => loadPage(ctx, "/notes/[id]", ["id"]),
  ...pageRoute(["id"], { loading: Loading2, error: Error1, notFound: NotFound3 }),
});

export const routeTree = rootRoute.addChildren([page0Route, page1Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
