// Generated by `airtty build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "airtty/route-tree";
import Layout0 from "./layout";
import Layout1 from "./(app)/layout";
import Layout2 from "./(app)/repos/[repo]/layout";
import Layout3 from "./(app)/repos/[repo]/pulls/[number]/layout";
import Loading4 from "./(app)/loading";
import Loading5 from "./(app)/repos/[repo]/loading";
import Loading6 from "./(app)/repos/[repo]/pulls/[number]/loading";

const rootRoute = createRootRoute(Layout0);
const layout0Route = createRoute({
  getParentRoute: () => rootRoute,
  id: "_app",
  ...layoutRoute(Layout1, []),
});
const layout1Route = createRoute({
  getParentRoute: () => layout0Route,
  path: "repos/$repo",
  ...layoutRoute(Layout2, ["repo"]),
});
const layout2Route = createRoute({
  getParentRoute: () => layout1Route,
  path: "pulls/$number",
  ...layoutRoute(Layout3, ["repo","number"]),
});
const page0Route = createRoute({
  getParentRoute: () => layout0Route,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/(app)", []),
  ...pageRoute([], Loading4),
});
const page1Route = createRoute({
  getParentRoute: () => layout1Route,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/(app)/repos/[repo]", ["repo"]),
  ...pageRoute(["repo"], Loading5),
});
const page2Route = createRoute({
  getParentRoute: () => layout2Route,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/(app)/repos/[repo]/pulls/[number]", ["repo","number"]),
  ...pageRoute(["repo","number"], Loading6),
});
const page3Route = createRoute({
  getParentRoute: () => layout2Route,
  path: "checks",
  loader: (ctx) => loadPage(ctx, "/(app)/repos/[repo]/pulls/[number]/checks", ["repo","number"]),
  ...pageRoute(["repo","number"], Loading6),
});
const page4Route = createRoute({
  getParentRoute: () => layout2Route,
  path: "files",
  loader: (ctx) => loadPage(ctx, "/(app)/repos/[repo]/pulls/[number]/files", ["repo","number"]),
  ...pageRoute(["repo","number"], Loading6),
});
const page5Route = createRoute({
  getParentRoute: () => layout1Route,
  path: "pulls/new",
  loader: (ctx) => loadPage(ctx, "/(app)/repos/[repo]/pulls/new", ["repo"]),
  ...pageRoute(["repo"], Loading5),
});
const page6Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "login",
  loader: (ctx) => loadPage(ctx, "/(public)/login", []),
  ...pageRoute([]),
});

export const routeTree = rootRoute.addChildren([layout0Route.addChildren([layout1Route.addChildren([layout2Route.addChildren([page2Route, page3Route, page4Route]), page1Route, page5Route]), page0Route]), page6Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
