// Generated by `airtty build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "airtty/route-tree";
import Layout0 from "./layout";
import NotFound1 from "./not-found";
import Loading2 from "./loading";
import Error3 from "./error";

const rootRoute = createRootRoute(Layout0, NotFound1);
const page0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/", []),
  ...pageRoute([], { loading: Loading2, error: Error3, notFound: NotFound1 }),
});
const page1Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "doc/$",
  loader: (ctx) => loadPage(ctx, "/doc/[...path]", ["path"], "path"),
  ...pageRoute(["path"], { loading: Loading2, error: Error3, notFound: NotFound1, splat: "path" }),
});

export const routeTree = rootRoute.addChildren([page0Route, page1Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
