// Generated by `luciole build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "@luciole-sh/core/route-tree";
import Layout0 from "./layout";
import Loading1 from "./loading";
import Error2 from "./error";

const rootRoute = createRootRoute(Layout0);
const page0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/", []),
  ...pageRoute([], { loading: Loading1, error: Error2 }),
});

export const routeTree = rootRoute.addChildren([page0Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
