// Generated by `luciole build` from app/. Do not edit: route files are the source.
import { createRoute } from "@tanstack/react-router";
import {
  layoutRoute,
  loadPage,
  pageRoute,
  rootRoute as createRootRoute,
  type TerminalRouter,
} from "luciole/route-tree";
import Layout0 from "./layout";

const rootRoute = createRootRoute(Layout0);
const page0Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: (ctx) => loadPage(ctx, "/", []),
  ...pageRoute([]),
});
const page1Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "cache",
  loader: (ctx) => loadPage(ctx, "/cache", []),
  ...pageRoute([]),
});
const page2Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "components",
  loader: (ctx) => loadPage(ctx, "/components", []),
  ...pageRoute([]),
});
const page3Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "conditions",
  loader: (ctx) => loadPage(ctx, "/conditions", []),
  ...pageRoute([]),
});
const page4Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "console",
  loader: (ctx) => loadPage(ctx, "/console", []),
  ...pageRoute([]),
});
const page5Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "input",
  loader: (ctx) => loadPage(ctx, "/input", []),
  ...pageRoute([]),
});
const page6Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "router",
  loader: (ctx) => loadPage(ctx, "/router", []),
  ...pageRoute([]),
});

export const routeTree = rootRoute.addChildren([page0Route, page1Route, page2Route, page3Route, page4Route, page5Route, page6Route]);

declare module "@tanstack/react-router" {
  interface Register {
    router: TerminalRouter<typeof routeTree>;
  }
}
