// node build.mjs — master/*.png (edited by hand, e.g. in Aseprite) -> luciole-data.js
//
// master/color.png    RGBA sprite at 1x, transparent background
// master/classes.png  flat colour per role, same size (see CLASS_COLOURS)
// master/light.png    greyscale lantern-light reception, same size (quantized to 0..3)
//
// Pixels are copied exactly: no quantization, so hand edits survive.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const CLASS_COLOURS = {
  // keep in sync with extract.py
  "128,128,128": 1, // body
  "198,232,90": 2, // lantern
  "255,160,0": 3, // antenna tip
  "48,112,255": 4, // eye (closed by the blink)
  "255,64,160": 5, // antenna stalk (lags behind the body)
};
const ALPH = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

function readPng(path) {
  const [w, h] = execFileSync("magick", ["identify", "-format", "%w %h", path])
    .toString()
    .split(" ")
    .map(Number);
  const data = execFileSync("magick", [path, "-depth", "8", "rgba:-"], { maxBuffer: 1 << 26 });
  return { w, h, px: (x, y) => [...data.subarray((y * w + x) * 4, (y * w + x) * 4 + 4)] };
}

const color = readPng("master/color.png");
const classes = readPng("master/classes.png");
const light = readPng("master/light.png");
const { w: W, h: H } = color;
for (const [name, img] of [
  ["classes", classes],
  ["light", light],
]) {
  if (img.w !== W || img.h !== H)
    throw new Error(`master/${name}.png is ${img.w}x${img.h}, expected ${W}x${H}`);
}

const palette = [];
const index = new Map();
const pal = (rgb) => {
  const key = rgb.join(",");
  if (!index.has(key)) {
    index.set(key, palette.length);
    palette.push(rgb);
  }
  return index.get(key);
};
const errors = [];
const pixels = [],
  classRows = [],
  lightRows = [];
const lanternColours = new Set();
for (let y = 0; y < H; y++) {
  let prow = "",
    crow = "",
    lrow = "";
  for (let x = 0; x < W; x++) {
    const [r, g, b, a] = color.px(x, y);
    const [cr, cg, cb, ca] = classes.px(x, y);
    const cls = ca < 128 ? 0 : CLASS_COLOURS[`${cr},${cg},${cb}`];
    if (cls === undefined)
      errors.push(`classes.png (${x},${y}): unknown class colour ${cr},${cg},${cb}`);
    if (a >= 128 !== cls > 0)
      errors.push(
        `(${x},${y}): color.png is ${a >= 128 ? "opaque" : "transparent"} but classes.png says ${cls ? "sprite" : "background"}`,
      );
    if (a < 128) {
      prow += ".";
      crow += "0";
      lrow += "0";
      continue;
    }
    const i = pal([r, g, b]);
    if (cls === 2) lanternColours.add(i);
    prow += ALPH[i];
    crow += cls ?? 1;
    lrow += Math.round((light.px(x, y)[0] / 255) * 3);
  }
  pixels.push(prow);
  classRows.push(crow);
  lightRows.push(lrow);
}
if (palette.length > ALPH.length)
  errors.push(`${palette.length} colours, the format holds ${ALPH.length}`);
if (errors.length) {
  console.error(
    errors.slice(0, 20).join("\n") + (errors.length > 20 ? `\n… ${errors.length - 20} more` : ""),
  );
  process.exit(1);
}
const lum = ([r, g, b]) => 0.3 * r + 0.59 * g + 0.11 * b;
const ramp = [...lanternColours].sort((a, b) => lum(palette[a]) - lum(palette[b]));
const hex = (c) => "#" + c.map((v) => v.toString(16).padStart(2, "0")).join("");
const rows = (a) => a.map((r) => `  ${JSON.stringify(r)},`).join("\n");

writeFileSync(
  "luciole-data.js",
  `// Generated by build.mjs from master/*.png — edit the PNGs, not this file.
// PIXELS: one char per pixel, index into PALETTE ('.' = transparent).
// CLASSES: 0 background, 1 body, 2 lantern, 3 antenna tip, 4 eye, 5 antenna stalk.
// LIGHT: lantern light received, 0 (none/occluded) .. 3 (full).
export const W = ${W}, H = ${H};
export const PALETTE = ${JSON.stringify(palette.map(hex))};
export const LANTERN_RAMP = ${JSON.stringify(ramp)}; // palette indices, dark -> bright
export const PIXELS = [
${rows(pixels)}
];
export const CLASSES = [
${rows(classRows)}
];
export const LIGHT = [
${rows(lightRows)}
];
`,
);
console.log(
  `luciole-data.js: ${W}x${H}, ${palette.length} colours, lantern ramp ${ramp.length} steps`,
);
