/**
 * The Codex app-server protocol types coder uses, generated from the installed `codex`
 * (its protocol is experimental and changes between versions):
 *
 *   bun scripts/coder/codex-types.ts
 *
 * runs `codex app-server generate-ts --experimental` and copies only the types the adapter
 * names, with everything they import, to examples/coder/server/adapters/codex-protocol/,
 * next to the version they come from (version.ts). The adapter checks it at start.
 */
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";

const OUT = resolve(import.meta.dir, "../../examples/coder/server/adapters/codex-protocol");
// Requests coder sends, notifications and requests it reads.
const ROOTS = [
  "InitializeParams",
  "InitializeResponse",
  "v2/ThreadStartParams",
  "v2/ThreadStartResponse",
  "v2/ThreadResumeParams",
  "v2/ThreadResumeResponse",
  "v2/ThreadListParams",
  "v2/ThreadListResponse",
  "v2/ThreadReadParams",
  "v2/ThreadReadResponse",
  "v2/TurnStartParams",
  "v2/TurnSteerParams",
  "v2/TurnInterruptParams",
  "v2/ThreadCompactStartParams",
  "v2/ModelListParams",
  "v2/ModelListResponse",
  "v2/SkillsListParams",
  "v2/SkillsListResponse",
  "v2/GetAccountParams",
  "v2/GetAccountResponse",
  "v2/GetAccountRateLimitsResponse",
  "v2/ThreadItem",
  "v2/CommandExecutionRequestApprovalParams",
  "v2/CommandExecutionRequestApprovalResponse",
  "v2/FileChangeRequestApprovalParams",
  "v2/FileChangeRequestApprovalResponse",
  "v2/ToolRequestUserInputParams",
  "v2/ToolRequestUserInputResponse",
  "v2/TurnStartedNotification",
  "v2/TurnCompletedNotification",
  "v2/ItemStartedNotification",
  "v2/ItemCompletedNotification",
  "v2/AgentMessageDeltaNotification",
  "v2/ReasoningSummaryTextDeltaNotification",
  "v2/CommandExecutionOutputDeltaNotification",
  "v2/TurnPlanUpdatedNotification",
  "v2/ThreadTokenUsageUpdatedNotification",
  "v2/AccountRateLimitsUpdatedNotification",
  "v2/ServerRequestResolvedNotification",
  "v2/ErrorNotification",
];

const version = Bun.spawnSync(["codex", "--version"])
  .stdout.toString()
  .trim()
  .replace(/^codex-cli\s+/, "");
const generated = mkdtempSync(join(tmpdir(), "codex-ts-"));
try {
  const run = Bun.spawnSync([
    "codex",
    "app-server",
    "generate-ts",
    "--out",
    generated,
    "--experimental",
  ]);
  if (run.exitCode !== 0) throw new Error(run.stderr.toString());
  const wanted = new Set<string>();
  const visit = (name: string) => {
    const file = join(generated, `${name}.ts`);
    if (wanted.has(file)) return;
    wanted.add(file);
    for (const match of readFileSync(file, "utf8").matchAll(/from "(\.{1,2}\/[^"]+)"/g)) {
      const target = relative(generated, resolve(dirname(file), match[1] ?? ""));
      visit(target);
    }
  };
  for (const root of ROOTS) visit(root);
  rmSync(OUT, { recursive: true, force: true });
  for (const file of wanted) {
    const to = join(OUT, relative(generated, file));
    mkdirSync(dirname(to), { recursive: true });
    copyFileSync(file, to);
  }
  writeFileSync(
    join(OUT, "version.ts"),
    `// GENERATED by scripts/coder/codex-types.ts: the codex these types come from.\nexport const CODEX_PROTOCOL_VERSION = ${JSON.stringify(version)};\n`,
  );
  console.log(`codex ${version}: ${wanted.size} files in ${relative(process.cwd(), OUT)}`);
} finally {
  rmSync(generated, { recursive: true, force: true });
}
