/**
 * Writes server/template.gen.ts from template/: the files studio copies into a new
 * project, as strings in the Server's bundle (they then exist wherever studio runs, a
 * compiled binary included). `--check` fails when the generated module is out of date.
 *
 *   bun examples/studio/scripts/template.ts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SOURCE = join(ROOT, "template");
const OUTPUT = join(ROOT, "server/template.gen.ts");
// Written by the build or by studio in a project, never part of the template.
const SKIPPED = /(^|\/)(\.airtty|\.airtty-studio|node_modules|data)(\/|$)|routeTree\.gen\.ts$/;

const files = [...new Bun.Glob("**/*").scanSync({ cwd: SOURCE, dot: true })]
  .filter((file) => !SKIPPED.test(file))
  .sort();
const entries = files
  .map(
    (file) =>
      `  ${JSON.stringify(file)}: ${JSON.stringify(readFileSync(join(SOURCE, file), "utf8"))},`,
  )
  .join("\n");
const text = `// Generated by examples/studio/scripts/template.ts from examples/studio/template: do not edit.
/** The starter project studio hands the harness: path → content. */
export const TEMPLATE: Readonly<Record<string, string>> = {
${entries}
};
`;
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {}
  if (current !== text) {
    console.error(`${OUTPUT} is out of date: run bun examples/studio/scripts/template.ts`);
    process.exit(1);
  }
} else writeFileSync(OUTPUT, text);
